### PR TITLE
Add Windows support to system notifier 

### LINKED ISSUE #3: Add System Notifier support for Linux and Windows
This should be pretty easy, you just need to add a block [here](https://github.com/epwalsh/pomo.nvim/blob/d8df96e145a4fdec78c0ab9987c6ebeeba000da5/lua/pomo/notifier.lua#L151) with an OS call to whatever would trigger a notification on that OS. I just don't have a way to test.

### PR DESCRIPTION
**Pull request by jmartinn**
This pull request introduces Windows notification support for the System Notifier, extending functionality in addition to the existing support for macOS and Linux. This enhancement addresses the existing issue of platform-specific notifications and aims to provide a seamless user experience across all major operating systems.

## **Changes Proposed:**
- Windows Notifications: Implement notifications using native PowerShell commands without requiring external dependencies. So we can use it out of the box.

## **Rationale:**

The current implementation of the notification system only supports macOS, using AppleScript, and Linux. This pull request aims to provide an inclusive solution that accommodates users on Windows An alternative approach was considered (using the BurntToast PowerShell module for Windows; see #15), but it was not quite accurate in my opinion due to its dependency requirements which could complicate the setup process for users. My proposed solution uses native system capabilities to ensure broader compatibility and ease of use.

## **Implementation Details:**

```lua
-- Windows Notification
elseif util.get_os() == util.OS.Windows then
    os.execute(string.format([[
        PowerShell -Command "Add-Type -AssemblyName System.Windows.Forms;
        $notify = New-Object System.Windows.Forms.NotifyIcon;
        $notify.Icon = [System.Drawing.SystemIcons]::Information;
        $notify.BalloonTipIcon = [System.Windows.Forms.ToolTipIcon]::Info;
        $notify.BalloonTipText = 'Timer #%d, %s%s';
        $notify.BalloonTipTitle = 'Timer done!';
        $notify.Visible = $true;
        $notify.ShowBalloonTip(10000);" ]],
        self.timer.id,
        util.format_time(self.timer.time_limit),
        repetitions_str
    ))
```

## **Conclusion:**

This update ensures that all users, regardless of their operating system, can benefit from the same level of functionality when using the Pomodoro timer plugin. By leveraging native system features, we maximize compatibility and maintain ease of use without additional dependencies.

### CODE REVIEW

**Comment by jmartinn** [comment]
> **Note:** This would completely close / solve #3

**Review by epwalsh — COMMENTED** [review]
@jmartinn this is great! Thanks a lot. Can you just update the note in the README on line 121 that still says the sys notifier is only available on MacOS natively.

**Comment by jmartinn** [comment]
@epwalsh sure! Sorry for the late reply btw. I've changed the line you've mentioned and deleted the line 122 which contained the url to track the issue

**Review by epwalsh — APPROVED** [review]
LGTM!

**Comment by lihuax-me** [comment]
Thank you very much for the PR you provided

But I noticed a small issue. Did you forget to add Windows to `SystemNotifier.supported_oss`?

Additionally, I found that simplifying the PowerShell command to a single line string is necessary for it to work properly on my computer. That is: 

```lua
SystemNotifier.supported_oss = { util.OS.Darwin, util.OS.Linux, util.OS.Windows }

-- ....

elseif util.get_os() == util.OS.Windows then
    os.execute(string.format(
      [[
        PowerShell -Command "Add-Type -AssemblyName System.Windows.Forms; $notify = New-Object System.Windows.Forms.NotifyIcon; $notify.Icon = [System.Drawing.SystemIcons]::Information; $notify.BalloonTipIcon = [System.Windows.Forms.ToolTipIcon]::Info; $notify.BalloonTipText = 'Timer #%d, %s%s'; $notify.BalloonTipTitle = 'Timer done!'; $notify.Visible = $true; $notify.ShowBalloonTip(10000);"
      ]],
      self.timer.id,
      util.format_time(self.timer.time_limit),
      repetitions_str
    ))
```

**Pull request merged**
